<?xml version="1.0" encoding="utf-8"?>
<!-- A compiler setting with no entry in the mapping table. Guessing is how a build quietly stops matching MSBuild's. -->
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><ConfigurationType>Application</ConfigurationType></PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <EnableEnhancedInstructionSet>AdvancedVectorExtensions512</EnableEnhancedInstructionSet>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
