<?xml version="1.0" encoding="utf-8"?>
<!-- A condition in a syntax this evaluator does not implement. -->
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><ConfigurationType>Application</ConfigurationType></PropertyGroup>
  <PropertyGroup Condition="'$(Version)' &gt;= '3'">
    <Something>yes</Something>
  </PropertyGroup>
</Project>
